name: Build and Trigger Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME_FRONTEND: ${{ secrets.DOCKERHUB_USERNAME }}/appphim-frontend
  IMAGE_NAME_BACKEND: ${{ secrets.DOCKERHUB_USERNAME }}/appphim-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      deploy_tag: ${{ steps.extract_version.outputs.tag }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from commit message
        id: extract_version
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          echo "Commit Message: $COMMIT_MSG"
          
          # Tìm định dạng phiên bản chuẩn (vX.Y.Z hoặc X.Y.Z)
          if [[ "$COMMIT_MSG" =~ \(([vV]?[0-9]+\.[0-9]+\.[0-9]+[a-zA-Z0-9-]*)\) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "Valid version format found: $VERSION"
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            VERSION="$SHORT_SHA"
            echo "No valid version format ({vX.Y.Z}) found. Defaulting to short commit hash: $VERSION"
          fi
          echo "tag=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.IMAGE_NAME_BACKEND }}:${{ steps.extract_version.outputs.tag }}
            ${{ env.IMAGE_NAME_BACKEND }}:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.IMAGE_NAME_FRONTEND }}:${{ steps.extract_version.outputs.tag }}
            ${{ env.IMAGE_NAME_FRONTEND }}:latest

  trigger-webhook:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Call deploy webhook
        if: github.event_name != 'pull_request'
        run: |
          if [[ -n "${{ secrets.DEPLOY_HOOK_URL }}" ]]; then 
            echo "Triggering deploy for tag: ${{ needs.build-and-push.outputs.deploy_tag }}"
            curl -X GET "${{ secrets.DEPLOY_HOOK_URL }}?repo=${{ secrets.DOCKERHUB_USERNAME }}&name=appphim&tag=${{ needs.build-and-push.outputs.deploy_tag }}"
          else
            echo "No deploy hook URL set, skipping."
          fi
